version: "2"
volumes:
  notebooks:
services:
  app:
    build: ./app
    ports:
      - 80:80
  server:
    build: ./server
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    ports:
      - 5000
  jupyter:
    build: ./jupyter
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    volumes:
      - "notebooks:/home/jovyan/work"
    ports:
      - "8080:8080"
