FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.8.0-stretch

RUN apt update
RUN apt-get install libzmq3-dev
RUN pip install --upgrade pip
RUN pip install jupyter
RUN ipython kernel install
RUN mkdir ~/jupyter

CMD ["jupyter", "notebook", "--no-browser"]