FROM node:12.2.0-alpine as builder
RUN apk add git 
RUN git clone https://github.com/nathanrpage97/liquid-crystal-app.git --branch v0.1.0
WORKDIR /liquid-crystal-app
RUN npm install --silent
RUN npm run build

FROM nginx:1.16.0-alpine
COPY --from=builder /liquid-crystal-app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]