FROM python:3.8.0-alpine3.10

RUN apk add git

WORKDIR /usr/src/server

RUN pip install git+https://github.com/nathanrpage97/liquid-crystal-server.git@v0.0.3

CMD ["python", "-m", "liquid_crystal_server"]